export const categories = [
  {
    id: 1,
    name: "Vehicle",
    color: "text-purple-500",
    icon: "🚗",
    subCategories: [
      { name: "Vehicle", icon: "🚗" },
      { name: "Fuel", icon: "⛽" },
      { name: "Leasing", icon: "📄" },
      { name: "Parking", icon: "🅿️" },
      { name: "Rentals", icon: "🔑" },
      { name: "Vehicle insurance", icon: "📋" },
    ],
  },
  {
    id: 2,
    name: "Shopping",
    color: "text-sky-500",
    icon: "🛍️",
    subCategories: [
      { name: "Shopping", icon: "🛍️" },
      { name: "Clothes", icon: "👕" },
      { name: "Gift & Joy", icon: "🎁" },
      { name: "Electronics", icon: "📱" },
    ],
  },
  {
    id: 3,
    name: "Food & Dining",
    color: "text-green-500",
    icon: "🍽️",
    subCategories: [
      { name: "Groceries", icon: "🛒" },
      { name: "Restaurants", icon: "🍴" },
      { name: "Takeout", icon: "🍕" },
      { name: "Delivery", icon: "🍔" },
    ],
  },
  {
    id: 4,
    name: "Entertainment",
    color: "text-red-500",
    icon: "🎬",
    subCategories: [
      { name: "Movies", icon: "🎥" },
      { name: "Concerts", icon: "🎶" },
      { name: "Games", icon: "🎮" },
      { name: "Streaming Services", icon: "📺" },
    ],
  },
  {
    id: 5,
    name: "Health & Fitness",
    color: "text-teal-500",
    icon: "💪",
    subCategories: [
      { name: "Gym Membership", icon: "🏋️‍♀️" },
      { name: "Medical Bills", icon: "💊" },
      { name: "Therapy", icon: "🧠" },
      { name: "Supplements", icon: "💊" },
      { name: "Fitness Equipment", icon: "🏃‍♂️" },
    ],
  },
  {
    id: 6,
    name: "Utilities",
    color: "text-blue-500",
    icon: "💡",
    subCategories: [
      { name: "Electricity", icon: "⚡" },
      { name: "Water", icon: "🚰" },
      { name: "Internet", icon: "🌐" },
      { name: "Phone", icon: "📱" },
      { name: "Gas", icon: "🔥" },
    ],
  },
  {
    id: 7,
    name: "Housing",
    color: "text-orange-500",
    icon: "🏠",
    subCategories: [
      { name: "Rent", icon: "🏠" },
      { name: "Mortgage", icon: "🏡" },
      { name: "Repairs", icon: "🔧" },
      { name: "Furniture", icon: "🛋️" },
      { name: "Cleaning", icon: "🧹" },
    ],
  },
  {
    id: 8,
    name: "Travel",
    color: "text-indigo-500",
    icon: "✈️",
    subCategories: [
      { name: "Flights", icon: "✈️" },
      { name: "Hotels", icon: "🏨" },
      { name: "Car Rentals", icon: "🚗" },
      { name: "Excursions", icon: "🏖️" },
      { name: "Visa & Passport", icon: "📄" },
    ],
  },
  {
    id: 9,
    name: "Education",
    color: "text-yellow-500",
    icon: "🎓",
    subCategories: [
      { name: "Tuition", icon: "📚" },
      { name: "Books", icon: "📖" },
      { name: "Online Courses", icon: "💻" },
      { name: "Workshops", icon: "🖥️" },
    ],
  },
  {
    id: 10,
    name: "Family & Childcare",
    color: "text-pink-500",
    icon: "👨‍👩‍👧‍👦",
    subCategories: [
      { name: "Childcare", icon: "👶" },
      { name: "School Fees", icon: "🎒" },
      { name: "Child's Activities", icon: "⚽" },
      { name: "Toys & Games", icon: "🧸" },
    ],
  },
  {
    id: 11,
    name: "Savings & Investments",
    color: "text-lime-500",
    icon: "💰",
    subCategories: [
      { name: "Savings Account", icon: "🏦" },
      { name: "Stocks", icon: "📈" },
      { name: "Bonds", icon: "💸" },
      { name: "Cryptocurrency", icon: "₿" },
      { name: "Retirement Fund", icon: "💼" },
    ],
  },
  {
    id: 12,
    name: "Personal Care",
    color: "text-pink-600",
    icon: "💅",
    subCategories: [
      { name: "Haircuts", icon: "💇‍♀️" },
      { name: "Skincare", icon: "🧴" },
      { name: "Cosmetics", icon: "💄" },
      { name: "Nail Care", icon: "💅" },
    ],
  },
  {
    id: 13,
    name: "Subscriptions",
    color: "text-gray-500",
    icon: "📅",
    subCategories: [
      { name: "Magazines", icon: "📖" },
      { name: "Software", icon: "💻" },
      { name: "Music", icon: "🎶" },
      { name: "Cloud Storage", icon: "☁️" },
    ],
  },
  {
    id: 14,
    name: "Charity & Donations",
    color: "text-teal-600",
    icon: "🤝",
    subCategories: [
      { name: "Donations", icon: "💸" },
      { name: "Charity Events", icon: "🎉" },
      { name: "Fundraising", icon: "💰" },
    ],
  },
  {
    id: 15,
    name: "Miscellaneous",
    color: "text-gray-700",
    icon: "📂",
    subCategories: [
      { name: "Gifts", icon: "🎁" },
      { name: "Miscellaneous Expenses", icon: "🛠️" },
    ],
  },
];
